"""seeker_v2.main — multi-process orchestrator + GUI/WS server.

Architecture:
  capture procs (EO, thermal, radar) → shm rings + queues
                                       ↓
                                  inference proc
                                       ↓
                                  fusion proc
                                       ↓
                              MAIN proc (this file)
                              - asyncio FastAPI WS server
                              - reads frame rings + fused_q
                              - serves GUI to browser

Each capture/inference/fusion is a separate OS process with its own
GIL. Main process runs only async I/O — no CPU-bound work — so the
event loop can sustain 30+ Hz WS pushes without backpressure cascades.

Lifecycle:
  1. Parse args, load config
  2. Set up multiprocessing context ("spawn" — works on aarch64 + Windows)
  3. Spawn child processes; each owns its sensor + shm ring
  4. Start FastAPI server (uvicorn) in same loop
  5. Aggregator coroutine reads frame rings + queues, builds WS payload
  6. SIGTERM handler: send shutdown to all children, wait, unlink shm
"""
from __future__ import annotations

import argparse
import asyncio
import logging
import multiprocessing as mp
import os
import signal
import sys
import time
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Optional

import numpy as np

# Module-level import so FastAPI's get_type_hints() can resolve the
# `ws: WebSocket` annotation in the WS handler. Without this, the
# annotation (a string under `from __future__ import annotations`)
# resolves to None, FastAPI treats the param as a missing dependency,
# and every WS upgrade returns HTTP 403.
from fastapi import WebSocket, Request as _Request  # noqa: E402

log = logging.getLogger("seeker_v2.main")


# ── Config loader (yaml or sane defaults) ──────────────────────────────
def load_config(path: Optional[str]) -> dict:
    if path and Path(path).exists():
        try:
            import yaml
            with open(path) as f:
                return yaml.safe_load(f) or {}
        except Exception as e:
            log.warning("config load failed (%s): %r", path, e)
    return {}


def _build_cfgs(cfg: dict):
    """Translate a v1-style app_config.yaml into v2 process configs."""
    from seeker_v2.processes.eo_capture import EOCaptureConfig
    from seeker_v2.processes.thermal_capture import ThermalCaptureConfig
    from seeker_v2.processes.radar_capture import RadarCaptureConfig
    from seeker_v2.processes.inference import InferenceConfig
    from seeker_v2.processes.fusion import FusionConfig

    eo_cfg = cfg.get("eo", {})
    thermal_cfg = cfg.get("thermal", {})
    classifier_cfg = cfg.get("classifier", {})

    # /dev/v4l/by-id/ symlinks ALWAYS point at the right capture interface
    # (video-index0 = streaming, video-index1 = metadata). These are auto-
    # generated by the kernel — no custom udev rule needed. Stable across
    # USB re-enumeration.
    eo = EOCaptureConfig(
        dev_path="/dev/v4l/by-id/usb-Leopard_Imaging_LI-IMX568_0000000001-video-index0",
        initial_exposure_ext=int(
            (eo_cfg.get("auto_exposure", {}) or {}).get("initial_exposure_ext", 1264)
        ),
    )
    thermal = ThermalCaptureConfig(
        dev_path="/dev/v4l/by-id/usb-FLIR_Boson_84778-video-index0",
        target_fps=int(thermal_cfg.get("target_fps", 60)),
        heat_tophat_kernel=11,
        jpeg_quality=int(
            (cfg.get("gui", {}) or {}).get("thermal_jpeg_quality", 70)
        ),
    )
    radar = RadarCaptureConfig(
        data_port="/dev/seeker_radar_data",
    )
    inference = InferenceConfig(
        eo_engine_path=str(
            (cfg.get("eo", {}).get("classifier", {}) or {}).get(
                "model", "models/seeker_eo_v3.engine"
            )
        ),
        eo_classify_interval=2,
        thermal_engine_path=str(
            classifier_cfg.get(
                "classifier_hv_model", "models/seeker_thermal_hv.engine"
            )
        ),
        thermal_classify_interval=int(
            classifier_cfg.get("classify_interval_frames", 4) or 4
        ),
        thermal_conf=float(classifier_cfg.get("classifier_hv_conf", 0.55)),
    )
    fusion = FusionConfig(
        rate_hz=25.0,
        eo_hfov_deg=float(eo_cfg.get("hfov_deg", 11.1)),
        eo_vfov_deg=float(eo_cfg.get("vfov_deg", 9.23)),
        thermal_hfov_deg=float(thermal_cfg.get("hfov_deg", 75.0)),
        thermal_vfov_deg=float(thermal_cfg.get("vfov_deg", 60.0)),
    )
    return eo, thermal, radar, inference, fusion


# ── Process registry ──────────────────────────────────────────────────
class ProcReg:
    """Hold all spawned children + queues + shutdown logic."""

    def __init__(self):
        self.eo_proc = None
        self.eo_ctrl = None
        self.eo_stats = None
        self.eo_jpeg_q = None
        self.thermal_proc = None
        self.thermal_ctrl = None
        self.thermal_stats = None
        self.thermal_jpeg_q = None
        # Latest JPEGs cached here by the aggregator coroutine, served
        # by /api/snapshot/{eo,thermal}.jpg.
        self.last_eo_jpeg: bytes = b""
        self.last_eo_jpeg_id: int = -1
        self.last_thermal_jpeg: bytes = b""
        self.last_thermal_jpeg_id: int = -1
        self.last_thermal_heat: list = []
        self.radar_proc = None
        self.radar_ctrl = None
        self.radar_targets_q = None
        self.radar_stats = None
        # In-process v1 managers (radar/gimbal/recorder live in this process)
        self.v1_radar = None
        self.v1_gimbal = None
        self.v1_recorder = None
        # GUI control state (set by HTTP/WS commands)
        self.tracked_target_id = None
        self.tracked_heat_id = None
        self.recording_active = False
        self.inference_proc = None
        self.inference_ctrl = None
        self.eo_det_q = None
        self.thermal_det_q = None
        self.inference_stats = None
        self.fusion_proc = None
        self.fusion_ctrl = None
        self.fused_q = None
        self.fusion_stats = None

        # Frame rings (consumer-side, attached for reading)
        self.eo_ring = None
        self.thermal_ring = None

    def shutdown(self):
        log.info("ProcReg shutting down children...")
        # Send shutdown commands first
        for q in (self.eo_ctrl, self.thermal_ctrl, self.radar_ctrl,
                  self.inference_ctrl, self.fusion_ctrl):
            if q is not None:
                try:
                    q.put(("shutdown", None))
                except Exception:
                    pass

        # Close consumer rings
        for r in (self.eo_ring, self.thermal_ring):
            if r is not None:
                try:
                    r.close()
                except Exception:
                    pass

        # Join processes (with timeouts)
        for proc in (self.fusion_proc, self.inference_proc,
                     self.radar_proc, self.thermal_proc, self.eo_proc):
            if proc is None:
                continue
            try:
                proc.join(timeout=3.0)
                if proc.is_alive():
                    log.warning("force-terminating %s", proc.name)
                    proc.terminate()
                    proc.join(timeout=2.0)
                if proc.is_alive():
                    proc.kill()
            except Exception:
                pass


# ── FastAPI app + WS sender ───────────────────────────────────────────
def _build_fastapi_app(reg: ProcReg, cfg: dict):
    """Build the FastAPI app. Imports lazily so the orchestrator
    doesn't depend on FastAPI at module-load time."""
    from fastapi import FastAPI, WebSocket, WebSocketDisconnect
    from fastapi.responses import HTMLResponse, Response, FileResponse

    try:
        import orjson  # type: ignore
        def _dumps(obj) -> bytes:
            return orjson.dumps(obj, option=orjson.OPT_SERIALIZE_NUMPY)
    except Exception:
        import json
        def _dumps(obj) -> bytes:
            return json.dumps(obj, default=str).encode("utf-8")

    app = FastAPI(title="seeker_v2")
    # Note: CORSMiddleware on Starlette 0.44 with allow_origins=["*"] +
    # allow_credentials=True silently rejects WebSocket upgrades. It's
    # also unnecessary on a same-origin GUI. Don't add it.

    # Health endpoint
    @app.get("/healthz")
    async def healthz():
        return {"ok": True, "version": "2.0.0-alpha"}

    # ── Phase 2.5: drain capture JPEG queues into reg cache ───────────
    def _drain_jpeg_queues():
        """Pull the freshest JPEG from each capture's small queue.

        Capture processes push (frame_id, jpeg_bytes[, ...]) tuples
        into a maxsize=2 queue. We drain to the latest and stash on
        ProcReg. Called from the WS coroutine and the snapshot handlers.
        """
        if reg.eo_jpeg_q is not None:
            try:
                while True:
                    item = reg.eo_jpeg_q.get_nowait()
                    if not item:
                        break
                    reg.last_eo_jpeg_id, reg.last_eo_jpeg = item[0], item[1]
            except Exception:
                pass
        if reg.thermal_jpeg_q is not None:
            try:
                while True:
                    item = reg.thermal_jpeg_q.get_nowait()
                    if not item:
                        break
                    fid, jpeg = item[0], item[1]
                    heat = item[2] if len(item) > 2 else []
                    reg.last_thermal_jpeg_id, reg.last_thermal_jpeg = fid, jpeg
                    reg.last_thermal_heat = heat
            except Exception:
                pass

    # Snapshot endpoints — the GUI's <img> tag pulls these on RAF.
    # Cache-Control: no-store so the browser always re-fetches.
    @app.get("/api/snapshot/eo.jpg")
    async def snapshot_eo():
        _drain_jpeg_queues()
        if not reg.last_eo_jpeg:
            return Response(status_code=503, content=b"no frame yet")
        return Response(content=reg.last_eo_jpeg, media_type="image/jpeg",
                        headers={"Cache-Control": "no-store",
                                 "X-Frame-Id": str(reg.last_eo_jpeg_id)})

    @app.get("/api/snapshot/thermal.jpg")
    async def snapshot_thermal():
        _drain_jpeg_queues()
        if not reg.last_thermal_jpeg:
            return Response(status_code=503, content=b"no frame yet")
        return Response(content=reg.last_thermal_jpeg, media_type="image/jpeg",
                        headers={"Cache-Control": "no-store",
                                 "X-Frame-Id": str(reg.last_thermal_jpeg_id)})

    # Static assets — served via simple GET endpoint (NOT app.mount).
    # On Starlette 0.44 with FastAPI 0.124, app.mount("/static", StaticFiles(...))
    # breaks WebSocket routing (every /ws/* upgrade returns 403).
    # Replicating StaticFiles behavior with a single route handler.
    static_dir = (Path(__file__).parent / "gui" / "static").resolve()

    @app.get("/static/{path:path}")
    async def static_files(path: str):
        full = (static_dir / path).resolve()
        # Path-traversal guard
        try:
            full.relative_to(static_dir)
        except ValueError:
            return Response(status_code=404)
        if not full.is_file():
            return Response(status_code=404)
        return FileResponse(str(full))

    # Status endpoint
    @app.get("/api/status")
    async def status():
        s = {}
        for label, q in [("eo_stats", reg.eo_stats),
                         ("thermal_stats", reg.thermal_stats),
                         ("radar_stats", reg.radar_stats),
                         ("inference_stats", reg.inference_stats),
                         ("fusion_stats", reg.fusion_stats)]:
            if q is None:
                continue
            last = None
            # Drain to the freshest message; queue.Empty exits the loop.
            while True:
                try:
                    last = q.get_nowait()
                except Exception:
                    break
            if last is not None:
                s[label] = last
        return s

    # ── Stub HTTP endpoints used by the v1 GUI ────────────────────────
    # The v1 frontend hits these on load + on user input; we return
    # sensible defaults so the GUI doesn't error. State is held
    # in-process and echoed back as the GUI expects.
    _config_state = {
        "thermal": {"available": True, "zoom_preset": "full",
                    "min_area_px": 8, "tophat_kernel": 11, "mad_k": 6.0},
        "heat_detector": {"available": True, "min_area_px": 8,
                          "tophat_kernel": 11, "mad_k": 6.0},
        "eo_exposure": {"available": True, "auto": True,
                        "exposure_ext": 1264, "gain": 0},
        "eo_lowlight": {"available": True, "enabled": False, "boost_db": 6.0},
    }
    @app.get("/api/config/{key}")
    async def get_config(key: str):
        return _config_state.get(key, {"available": False})

    @app.post("/api/config/{key}")
    async def post_config(key: str, request: _Request):
        body = await request.json() or {}
        if key in _config_state:
            _config_state[key].update(body)
        # Propagate to capture processes where applicable.
        # EO exposure → eo_capture ctrl_q
        if key == "eo_exposure" and reg.eo_ctrl is not None:
            new_exp = body.get("exposure_ext")
            if new_exp is not None:
                try: reg.eo_ctrl.put_nowait(("exposure_ext", int(new_exp)))
                except Exception as e: log.warning("eo_ctrl exp: %r", e)
        # Thermal zoom preset → wire payload (v2 has fixed-optics Boson;
        # zoom is GUI-side cropping driven by this field in the envelope).
        # heat_detector / eo_lowlight currently only stored in state;
        # capture-side propagation is next iter.
        return {"ok": True, **_config_state.get(key, {})}

    # ── Gimbal control endpoints ─────────────────────────────────────
    @app.post("/api/gimbal/absolute")
    async def gimbal_absolute(request: _Request):
        body = await request.json()
        if reg.v1_gimbal is None:
            return {"ok": False, "error": "no gimbal manager"}
        try:
            pan = float(body.get("pan", 0.0))
            tilt = float(body.get("tilt", 0.0))
            reg.v1_gimbal.set_manual_absolute(pan, tilt)
            return {"ok": True, "pan": pan, "tilt": tilt}
        except Exception as e:
            return {"ok": False, "error": repr(e)}

    @app.post("/api/gimbal/home")
    async def gimbal_home():
        if reg.v1_gimbal is None:
            return {"ok": False}
        try:
            reg.v1_gimbal.set_home()
            return {"ok": True}
        except Exception as e:
            return {"ok": False, "error": repr(e)}

    # ── Track / heat-track lock ──────────────────────────────────────
    @app.post("/api/track")
    async def set_track(request: _Request):
        body = await request.json()
        tid = body.get("target_id")
        reg.tracked_target_id = int(tid) if tid is not None else None
        reg.tracked_heat_id = None  # heat lock superseded by fused lock
        return {"ok": True, "tracked_target_id": reg.tracked_target_id}

    @app.post("/api/heat_track")
    async def set_heat_track(request: _Request):
        body = await request.json()
        hid = body.get("heat_id")
        reg.tracked_heat_id = int(hid) if hid is not None else None
        reg.tracked_target_id = None
        return {"ok": True, "tracked_heat_id": reg.tracked_heat_id}

    # ── Recording (v1's JSONLRecorder) ───────────────────────────────
    @app.post("/api/recording/start")
    async def recording_start():
        if reg.v1_recorder is None:
            return {"ok": False, "error": "no recorder"}
        try:
            reg.v1_recorder.start()
            reg.recording_active = True
            return {"ok": True}
        except Exception as e:
            return {"ok": False, "error": repr(e)}

    @app.post("/api/recording/stop")
    async def recording_stop():
        if reg.v1_recorder is None:
            return {"ok": False}
        try:
            reg.v1_recorder.stop()
            reg.recording_active = False
            return {"ok": True}
        except Exception as e:
            return {"ok": False, "error": repr(e)}

    @app.get("/api/recording/state")
    async def recording_state():
        return {"recording": reg.recording_active}

    # ── Extrinsic / illuminator / calibration stubs ──────────────────
    @app.get("/api/extrinsic")
    async def get_extrinsic():
        if reg.v1_radar is None:
            return {}
        return {
            "radar_az_bias_deg": float(getattr(reg.v1_radar, "az_bias_deg", 0.0)),
            "radar_el_bias_deg": float(getattr(reg.v1_radar, "el_bias_deg", 0.0)),
        }

    @app.post("/api/extrinsic")
    async def set_extrinsic(request: _Request):
        body = await request.json()
        if reg.v1_radar is None:
            return {"ok": False}
        if "radar_az_bias_deg" in body:
            reg.v1_radar.az_bias_deg = float(body["radar_az_bias_deg"])
        if "radar_el_bias_deg" in body:
            reg.v1_radar.el_bias_deg = float(body["radar_el_bias_deg"])
        return {"ok": True, **(await get_extrinsic())}

    @app.post("/api/illuminator")
    async def set_illuminator(request: _Request):
        body = await request.json()
        return {"ok": True, "state": body.get("state", "auto")}

    @app.get("/api/devices/cameras")
    async def list_cameras():
        return {"cameras": []}  # stub — v1 enumerates V4L2 indices

    # ── Stubs for the rest of v1's HTTP API (keeps GUI from 404'ing) ─
    @app.post("/api/radar/kick_lvds")
    async def radar_kick_lvds():
        return {"ok": False, "error": "no DCA1000 raw-ADC pipeline in v2"}

    @app.get("/api/radar/aa_diagnostics")
    async def radar_aa_diag():
        return {"available": False, "reason": "no DCA pipeline in v2"}

    @app.get("/api/eo/ae_state")
    async def eo_ae_state():
        # Surface what the probe ladder picked, if available via stats queue.
        return {"available": True, "ae_locked": True}

    @app.post("/api/config/eo")
    async def post_eo_config(request: _Request):
        body = await request.json()
        return {"ok": True, **body}

    # Health alias (v1 uses /health, my V2 has /healthz)
    @app.get("/health")
    async def health_alias():
        return {"ok": True}

    # ── v1-compatible WebSocket sender ─────────────────────────────────
    # Protocol mirrors gui/app.py exactly:
    #   • Shared "sensors" envelope at ws_fps Hz (text JSON).
    #   • Binary EO frames on every new EO frame:
    #       [4-byte LE hdr_len][JSON header][JPEG bytes]
    #   Both run as cooperating coroutines on the same WebSocket.
    @app.websocket("/ws/sensors")
    async def ws_sensors(ws: WebSocket):
        try:
            await ws.accept()
        except Exception as e:
            log.exception("ws.accept() failed: %r", e); return
        log.info("WS client connected")

        from seeker_v2 import wire_v1
        period = 1.0 / float((cfg.get("gui", {}) or {}).get("ws_fps", 30))
        eo_idle_poll_s = 0.005

        # Shared state held in closure (one per WS connection)
        last_eo_seq = -1
        last_thermal_seq = -1
        last_fused = []
        last_radar_targets = []
        last_radar_frame_id = 0
        last_radar_ts = 0.0
        last_eo_dets = []
        last_thermal_dets = []
        send_lock = asyncio.Lock()      # arbitrate text vs bytes sends

        # Drain producer queues into closure state. Called from both
        # senders so neither sees stale data.
        # NOTE: fusion is the SOLE consumer of eo_det_q / thermal_det_q
        # / radar_targets_q. It re-publishes those payloads inside its
        # fused_q envelope, so we only drain fused_q here. (See
        # processes/fusion.py — envelope keys: tracks, radar_targets,
        # eo_dets, thermal_dets, radar_frame_id.)
        def _drain_all():
            nonlocal last_fused, last_radar_targets
            nonlocal last_radar_frame_id, last_radar_ts
            nonlocal last_eo_dets, last_thermal_dets

            _drain_jpeg_queues()  # already updates reg.last_*_jpeg

            if reg.fused_q is not None:
                try:
                    while True:
                        msg = reg.fused_q.get_nowait()
                        if msg is None: break
                        last_fused          = msg.get("tracks", []) or []
                        last_radar_targets  = msg.get("radar_targets", []) or []
                        last_eo_dets        = msg.get("eo_dets", []) or []
                        last_thermal_dets   = msg.get("thermal_dets", []) or []
                        last_radar_frame_id = int(msg.get("radar_frame_id", 0))
                        last_radar_ts       = float(msg.get("ts", 0.0))
                except Exception: pass

        async def shared_sender():
            nonlocal last_eo_seq, last_thermal_seq
            try:
                while True:
                    t0 = time.monotonic()
                    _drain_all()

                    eo_desc = None; thermal_desc = None
                    if reg.eo_ring is not None:
                        eo_desc, seq = reg.eo_ring.latest()
                        if seq != last_eo_seq: last_eo_seq = seq
                    if reg.thermal_ring is not None:
                        thermal_desc, seq = reg.thermal_ring.latest()
                        if seq != last_thermal_seq: last_thermal_seq = seq

                    # Pull v1 BUS objects (radar / gimbal) — present
                    # when v1_managers spawned them.
                    try:
                        from seeker_v2 import v1_managers
                        v1_radar    = v1_managers.bus_get_radar()
                        v1_gimbal_s = v1_managers.bus_get_gimbal_state()
                        v1_radar_aa = v1_managers.bus_get_radar_aa()
                    except Exception:
                        v1_radar = v1_gimbal_s = v1_radar_aa = None

                    # Surface zoom_preset and config state from the
                    # in-memory _config_state so v1 GUI buttons stay in
                    # sync (active border / hover state).
                    th_zoom = (_config_state.get("thermal", {})
                               .get("zoom_preset", "full"))

                    msg = wire_v1.build_ws_message(
                        thermal_desc=thermal_desc,
                        thermal_jpeg_bytes=reg.last_thermal_jpeg or None,
                        # heat_dets ride the jpeg queue (see thermal_capture:
                        # jpeg_q.put((fid, bytes, heat_dets))); the FrameRing
                        # atomic publish only carries fixed fields, not meta.
                        thermal_heat_dets=reg.last_thermal_heat,
                        eo_desc=eo_desc,
                        eo_dets=last_eo_dets,
                        v1_radar_frame=v1_radar,
                        v1_gimbal_state=v1_gimbal_s,
                        v1_radar_aa_frame=v1_radar_aa,
                        radar_targets=last_radar_targets,
                        radar_last_frame_id=last_radar_frame_id,
                        radar_last_ts=last_radar_ts,
                        fused_tracks=last_fused,
                        tracked_target_id=reg.tracked_target_id,
                        tracked_heat_id=reg.tracked_heat_id,
                    )
                    # Override zoom_preset from config state (v1 GUI sync).
                    if "thermal" in msg:
                        msg["thermal"]["zoom_preset"] = th_zoom
                    text = _dumps(msg).decode("utf-8") if isinstance(_dumps(msg), bytes) else _dumps(msg)

                    async with send_lock:
                        try:
                            await ws.send_text(text)
                        except WebSocketDisconnect: raise
                        except Exception as e:
                            log.warning("ws shared send failed: %r", e); return

                    elapsed = time.monotonic() - t0
                    await asyncio.sleep(max(0.0, period - elapsed))
            except WebSocketDisconnect: return
            except Exception:
                log.exception("shared_sender died")

        async def eo_binary_sender():
            last_id = -1
            try:
                while True:
                    _drain_jpeg_queues()
                    fid = reg.last_eo_jpeg_id
                    if fid <= last_id or not reg.last_eo_jpeg:
                        await asyncio.sleep(eo_idle_poll_s); continue
                    last_id = fid

                    eo_desc = None
                    if reg.eo_ring is not None:
                        eo_desc, _ = reg.eo_ring.latest()

                    hdr, jpeg_bytes = wire_v1.eo_to_wire_split(
                        eo_desc, reg.last_eo_jpeg,
                        eo_dets_v2=last_eo_dets,
                    )
                    payload = wire_v1.build_eo_binary_frame(hdr, jpeg_bytes)

                    async with send_lock:
                        try:
                            await ws.send_bytes(payload)
                        except WebSocketDisconnect: raise
                        except Exception as e:
                            log.warning("ws eo binary send failed: %r", e); return
                    await asyncio.sleep(0.0)
            except WebSocketDisconnect: return
            except Exception:
                log.exception("eo_binary_sender died")

        async def receiver():
            """Handle commands sent FROM the GUI (mirror v1 gui/app.py:_receiver).

            Every command v1's main.js can wsSend() is handled here so
            every button in the v1 GUI does the same thing under V2 as
            under v1.
            """
            import json as _j
            try:
                async for raw in ws.iter_text():
                    try: cmd = _j.loads(raw)
                    except Exception: continue
                    op = cmd.get("command")
                    typ = cmd.get("type")
                    gm = reg.v1_gimbal
                    rm = reg.v1_radar

                    # ── Track / heat-track ────────────────────────────
                    if op == "track":
                        tid = cmd.get("track_id")
                        reg.tracked_target_id = int(tid) if tid is not None else None
                        reg.tracked_heat_id = None
                        if gm is not None:
                            try: gm.set_track_target(reg.tracked_target_id)
                            except Exception as e: log.warning("set_track_target: %r", e)
                        log.info("WS track -> %s", reg.tracked_target_id)
                    elif op == "track_heat":
                        hid = cmd.get("heat_id")
                        reg.tracked_heat_id = int(hid) if hid is not None else None
                        reg.tracked_target_id = None
                        if gm is not None:
                            try: gm.set_track_heat(reg.tracked_heat_id)
                            except Exception as e: log.warning("set_track_heat: %r", e)
                        log.info("WS track_heat -> %s", reg.tracked_heat_id)

                    # ── Gimbal control ────────────────────────────────
                    elif op == "gimbal_manual":
                        reg.tracked_target_id = None; reg.tracked_heat_id = None
                        if gm is not None:
                            try:
                                gm.set_manual_delta(
                                    float(cmd.get("delta_pan", 0.0)),
                                    float(cmd.get("delta_tilt", 0.0)),
                                )
                            except Exception as e: log.warning("set_manual_delta: %r", e)
                    elif op == "gimbal_absolute":
                        if reg.tracked_target_id is not None:
                            reg.tracked_target_id = None
                            if gm is not None:
                                try: gm.set_track_target(None)
                                except Exception: pass
                        if gm is not None:
                            try:
                                gm.set_manual_absolute(
                                    float(cmd.get("pan", 0.0)),
                                    float(cmd.get("tilt", 0.0)),
                                )
                            except Exception as e: log.warning("set_manual_absolute: %r", e)
                    elif op == "gimbal_home":
                        reg.tracked_target_id = None; reg.tracked_heat_id = None
                        if gm is not None:
                            try: gm.set_track_target(None); gm.set_track_heat(None); gm.set_home()
                            except Exception as e: log.warning("set_home: %r", e)
                        log.info("WS gimbal_home")

                    # ── Synthetic target (DRAW TARGET button) ─────────
                    elif typ == "synthetic_target" or op == "synthetic_target":
                        bbox = cmd.get("bbox")
                        if isinstance(bbox, (list, tuple)) and len(bbox) == 4:
                            try:
                                # Find a thermal manager — V2 doesn't have
                                # one but v1's synthetic-target plumbing is
                                # in ThermalManager. Stub: log + ack so the
                                # GUI doesn't error.
                                x, y, w, h = (int(v) for v in bbox)
                                log.info("WS synthetic_target bbox=%d,%d,%d,%d (V2 stub: no thermal mgr to seed)", x, y, w, h)
                            except Exception as e:
                                log.warning("synthetic_target bad bbox: %r", e)
                    elif typ == "clear_synthetic_target" or op == "clear_synthetic_target":
                        reg.tracked_heat_id = None
                        if gm is not None:
                            try: gm.set_track_heat(None)
                            except Exception: pass
                        log.info("WS clear_synthetic_target")

                    # ── Recording (REC pill, command:'record') ────────
                    elif op == "record":
                        on = bool(cmd.get("on", False))
                        if reg.v1_recorder is not None:
                            try:
                                if on and not reg.v1_recorder.is_recording:
                                    reg.v1_recorder.start()
                                    reg.recording_active = True
                                    log.info("WS record START")
                                elif not on and reg.v1_recorder.is_recording:
                                    reg.v1_recorder.stop()
                                    reg.recording_active = False
                                    log.info("WS record STOP")
                            except Exception as e: log.warning("record cmd: %r", e)
                    elif op in ("recording_start",):
                        if reg.v1_recorder is not None:
                            try: reg.v1_recorder.start(); reg.recording_active = True
                            except Exception as e: log.warning("rec start: %r", e)
                    elif op in ("recording_stop",):
                        if reg.v1_recorder is not None:
                            try: reg.v1_recorder.stop(); reg.recording_active = False
                            except Exception as e: log.warning("rec stop: %r", e)

                    # ── NIR / illuminator ────────────────────────────
                    elif op == "nir" or op == "illuminator":
                        # No NIR LED wired; just record state for echo.
                        pass

                    # ── Radar tuning (DEV tab sliders) ────────────────
                    elif op == "radar_tune":
                        if rm is not None and hasattr(rm, "set_tuning"):
                            try:
                                rm.set_tuning(
                                    snr_min_db          = cmd.get("snr_min_db"),
                                    max_range_m         = cmd.get("max_range_m"),
                                    az_half_deg         = cmd.get("az_half_deg"),
                                    speed_min_mps       = cmd.get("speed_min_mps"),
                                    range_min_m         = cmd.get("range_min_m"),
                                    cluster_eps_pos_m   = cmd.get("cluster_eps_pos_m"),
                                    cluster_eps_dop_mps = cmd.get("cluster_eps_dop_mps"),
                                    cluster_min_samples = cmd.get("cluster_min_samples"),
                                )
                            except Exception as e: log.warning("radar_tune: %r", e)
                    elif op == "set_radar_mode":
                        mode = str(cmd.get("mode", "")).lower()
                        if mode in ("stock", "ag", "aa") and rm is not None and hasattr(rm, "set_mode"):
                            try: rm.set_mode(mode)
                            except Exception as e: log.warning("set_radar_mode: %r", e)
                    elif op == "ag_tune":
                        if rm is not None and hasattr(rm, "update_ag_params"):
                            try: rm.update_ag_params(**{k: v for k, v in cmd.items() if k not in ("command",) and v is not None})
                            except Exception as e: log.warning("ag_tune: %r", e)
                    elif op == "aa_tune":
                        if rm is not None and hasattr(rm, "update_aa_params"):
                            try: rm.update_aa_params(**{k: v for k, v in cmd.items() if k not in ("command",) and v is not None})
                            except Exception as e: log.warning("aa_tune: %r", e)
                    elif op == "save_radar_mode_config":
                        try:
                            import json as _j2
                            from pathlib import Path as _P
                            mode = str(cmd.get("mode", "")).lower()
                            if mode in ("stock", "ag", "aa"):
                                d = _P("config"); d.mkdir(exist_ok=True)
                                f = d / "radar_modes.json"
                                store = {}
                                try: store = _j2.loads(f.read_text())
                                except Exception: pass
                                store[mode] = {k: v for k, v in cmd.items()
                                                if k not in ("command", "mode") and v is not None}
                                f.write_text(_j2.dumps(store, indent=2))
                                log.info("Saved radar mode %s to %s", mode, f)
                        except Exception as e: log.warning("save_radar_mode_config: %r", e)

                    # ── Extrinsic calibration sliders (DEV tab) ───────
                    elif op == "extrinsic_tune":
                        r_az = cmd.get("radar_az_bias_deg")
                        r_el = cmd.get("radar_el_bias_deg")
                        if rm is not None and (r_az is not None or r_el is not None):
                            try:
                                if hasattr(rm, "set_extrinsic"):
                                    rm.set_extrinsic(az_bias_deg=r_az, el_bias_deg=r_el)
                                else:
                                    if r_az is not None: rm.az_bias_deg = float(r_az)
                                    if r_el is not None: rm.el_bias_deg = float(r_el)
                            except Exception as e: log.warning("extrinsic radar: %r", e)
                    elif op == "extrinsic_tune_done":
                        pass
                    elif op == "extrinsic_save":
                        # Persist current biases via v1 calibration_store.
                        try:
                            from common import calibration_store
                            payload = {}
                            if rm is not None:
                                payload["radar_az"] = float(getattr(rm, "az_bias_deg", 0.0))
                                payload["radar_el"] = float(getattr(rm, "el_bias_deg", 0.0))
                            calibration_store.save(**payload)
                            log.info("extrinsic saved %r", payload)
                        except Exception as e: log.warning("extrinsic_save: %r", e)

                    else:
                        log.debug("WS unknown command: op=%r type=%r keys=%s",
                                   op, typ, list(cmd.keys()))
            except WebSocketDisconnect: return
            except Exception:
                log.exception("ws receiver died")

        # Run all three coroutines cooperatively; first to finish cancels.
        try:
            await asyncio.gather(shared_sender(), eo_binary_sender(), receiver())
        except WebSocketDisconnect:
            log.info("WS client disconnected")
        except Exception:
            log.exception("ws loop died")

    # Index page — serves the gui/index.html if present, else placeholder.
    gui_index = Path(__file__).parent / "gui" / "index.html"

    @app.get("/", response_class=HTMLResponse)
    async def index():
        if gui_index.exists():
            return HTMLResponse(gui_index.read_text(encoding="utf-8"))
        return """<!DOCTYPE html>
<html><head><title>seeker_v2</title></head>
<body style="background:#111;color:#0f0;font-family:monospace;padding:20px">
<h1>seeker_v2 alpha</h1>
<p>GUI not built (seeker_v2/gui/index.html missing).</p>
<p>WebSocket: <code>/ws/sensors</code> · Status: <a style="color:#0f0" href="/api/status">/api/status</a></p>
</body></html>"""

    return app


# ── Main entry point ───────────────────────────────────────────────────
def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="seeker_v2 multi-process orchestrator")
    parser.add_argument("--config", default="config/app_config.yaml",
                        help="Path to v1-style YAML config (optional).")
    parser.add_argument("--host", default="0.0.0.0",
                        help="HTTP/WS bind address")
    parser.add_argument("--port", type=int, default=8081,
                        help="HTTP/WS port (default 8081 to avoid v1 on 8080)")
    parser.add_argument("--no-eo", action="store_true")
    parser.add_argument("--no-thermal", action="store_true")
    parser.add_argument("--no-radar", action="store_true")
    parser.add_argument("--no-inference", action="store_true")
    parser.add_argument("--no-fusion", action="store_true")
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(name)s %(levelname)s %(message)s",
    )

    # Load config
    cfg = load_config(args.config)
    eo_cfg, thermal_cfg, radar_cfg, inference_cfg, fusion_cfg = _build_cfgs(cfg)
    log.info("config loaded; spawning processes...")

    # Use spawn context — works on Linux + macOS + Windows.
    mp_ctx = mp.get_context("spawn")

    reg = ProcReg()

    # ── Spawn capture processes ────────────────────────────────────
    if not args.no_eo:
        from seeker_v2.processes.eo_capture import spawn as eo_spawn
        (reg.eo_proc, reg.eo_ctrl, reg.eo_stats,
         reg.eo_jpeg_q) = eo_spawn(mp_ctx, eo_cfg)
        log.info("EO capture spawned (pid=%d)", reg.eo_proc.pid)

    if not args.no_thermal:
        from seeker_v2.processes.thermal_capture import spawn as t_spawn
        (reg.thermal_proc, reg.thermal_ctrl, reg.thermal_stats,
         reg.thermal_jpeg_q) = t_spawn(mp_ctx, thermal_cfg)
        log.info("thermal capture spawned (pid=%d)", reg.thermal_proc.pid)

    # Radar + Gimbal + Recorder: reuse v1's managers (in-process, threaded).
    # They publish to v1's BUS singleton in *this* process; wire_v1
    # reads from BUS to merge into the WS envelope.
    try:
        from seeker_v2 import v1_managers
        if not args.no_radar:
            reg.v1_radar = v1_managers.start_radar(args.config)
        reg.v1_gimbal   = v1_managers.start_gimbal(args.config)
        reg.v1_recorder = v1_managers.start_recorder(args.config)
    except Exception:
        log.exception("v1 manager start failed")

    # Attach consumer rings (main needs them to read frames into the WS payload).
    # Captures may take a few seconds to bring up shm (camera open + first frame),
    # so retry with backoff instead of a fixed sleep.
    from seeker_v2.processes.ipc import FrameRing
    def _attach_with_retry(shm_name, n_slots, frame_bytes, label, attempts=20):
        for i in range(attempts):
            try:
                ring = FrameRing.attach(shm_name, n_slots=n_slots, frame_bytes=frame_bytes)
                log.info("%s ring attached (try %d/%d)", label, i + 1, attempts)
                return ring
            except FileNotFoundError:
                time.sleep(0.5)
            except Exception as e:
                log.warning("%s ring attach unexpected: %r", label, e)
                time.sleep(0.5)
        log.warning("%s ring attach gave up after %d attempts", label, attempts)
        return None

    if not args.no_eo:
        reg.eo_ring = _attach_with_retry(
            eo_cfg.shm_name, eo_cfg.n_slots,
            eo_cfg.width * eo_cfg.height * 3, "EO",
        )
    if not args.no_thermal:
        reg.thermal_ring = _attach_with_retry(
            thermal_cfg.shm_name, thermal_cfg.n_slots,
            thermal_cfg.width * thermal_cfg.height * 3, "thermal",
        )

    if not args.no_inference:
        from seeker_v2.processes.inference import spawn as i_spawn
        (reg.inference_proc, reg.inference_ctrl, reg.eo_det_q,
         reg.thermal_det_q, reg.inference_stats) = i_spawn(
            mp_ctx, inference_cfg
        )
        log.info("inference spawned (pid=%d)", reg.inference_proc.pid)

    if not args.no_fusion:
        from seeker_v2.processes.fusion import spawn as f_spawn
        eo_dq = reg.eo_det_q if reg.eo_det_q is not None else mp_ctx.Queue()
        thermal_dq = reg.thermal_det_q if reg.thermal_det_q is not None else mp_ctx.Queue()
        radar_tq = reg.radar_targets_q if reg.radar_targets_q is not None else mp_ctx.Queue()
        (reg.fusion_proc, reg.fusion_ctrl, reg.fused_q,
         reg.fusion_stats) = f_spawn(
            mp_ctx, fusion_cfg, eo_dq, thermal_dq, radar_tq,
        )
        log.info("fusion spawned (pid=%d)", reg.fusion_proc.pid)

    # Build + run FastAPI WS server
    app = _build_fastapi_app(reg, cfg)
    try:
        import uvicorn
    except Exception:
        log.error("uvicorn not installed — run: pip install fastapi uvicorn[standard] orjson")
        reg.shutdown()
        return 1

    config = uvicorn.Config(
        app=app,
        host=args.host,
        port=args.port,
        log_level="info",
        loop="asyncio",
        ws="websockets",
        # NOTE: do NOT set forwarded_allow_ips here. With "*" uvicorn's
        # ProxyHeadersMiddleware silently rejects WebSocket upgrades
        # with HTTP 403. Default ("127.0.0.1") works fine.
    )
    server = uvicorn.Server(config)

    # Install signal handlers for clean shutdown
    def _on_sigint(*_):
        log.info("shutdown signal received")
        server.should_exit = True

    signal.signal(signal.SIGTERM, _on_sigint)
    signal.signal(signal.SIGINT, _on_sigint)

    try:
        log.info("starting server on http://%s:%d/", args.host, args.port)
        server.run()
    finally:
        reg.shutdown()

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
