/**
 *   @file  mmw_resDDM.h
 *
 *   @brief
 *      Defines partitioning of hardware resources (HWA, EDMA etc) among the
 *      DPCs and other components in the millimeter wave demo.
 *
 *  \par
 *  NOTE:
 *      (C) Copyright 2020-2025 Texas Instruments, Inc.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#ifndef MMW_DEMO_RES_H
#define MMW_DEMO_RES_H

#ifdef __cplusplus
extern "C" {
#endif

#include <drivers/edma.h>
#include <ti/common/syscommon.h>

/* DPUs */
#include <ti/datapath/dpu/rangeprocDDMA/rangeprochwaDDMA.h>
#include <ti/datapath/dpu/dopplerprocDDMA/dopplerprochwaDDMA.h>
#include <ti/datapath/dpu/rangecfarprocDDMA/rangecfarprochwa.h>

/*******************************************************************************
 * Resources for Object Detection DPC, currently the only DPC and hwa/edma
 * resource user in the demo.
 *******************************************************************************/
#define DPU_OBJECTDET_HWA_MEMBANK_SIZE_BYTES                                16384U

/* EDMA instance used*/
/* HWA can only be accessed through DSS*/
#define EDMA_DRV_INST_DSS_A                                        0U
#define EDMA_NUM_DMA_CHANNELS                                      64U

#define DPC_OBJDET_EDMA_INSTANCE                                   EDMA_DRV_INST_DSS_A

#define DPC_OBJDET_EDMA_SHADOW_BASE                                   EDMA_NUM_DMA_CHANNELS
#define DPC_OBJDET_HWA_WINDOW_RAM_OFFSET                              0U
#define DPC_OBJDEC_PARAMSET_START_IDX                                 0U

/* Range DPU */

#define DPC_OBJDET_DPU_RANGEPROC_PARAMSET_START_IDX                   DPC_OBJDEC_PARAMSET_START_IDX
#define DPU_RANGEPROCHWADDMA_NUM_HWA_PARAM_SETS                       DPU_RANGEPROCHWA_NUM_HWA_PARAM_SETS_DDMA

#define DPC_OBJDET_DPU_RANGEPROC_EDMA_INST_ID                         DPC_OBJDET_EDMA_INSTANCE

#define DPC_OBJDET_DPU_RANGEPROC_EDMAIN_CH                            EDMA_DSS_TPCC_A_EVT_RSS_ADC_CAPTURE_COMPLETE

#define DPC_OBJDET_DPU_RANGEPROC_EDMAIN_SHADOW                        (DPC_OBJDET_EDMA_SHADOW_BASE + 0U)
#define DPC_OBJDET_DPU_RANGEPROC_EDMAIN_EVENT_QUE                     0U
#define DPC_OBJDET_DPU_RANGEPROC_EDMAIN_SIG_CH                        EDMA_DSS_TPCC_A_EVT_HWA_DMA_REQ0
#define DPC_OBJDET_DPU_RANGEPROC_EDMAIN_SIG_SHADOW                    (DPC_OBJDET_EDMA_SHADOW_BASE + 1U)
#define DPC_OBJDET_DPU_RANGEPROC_EDMAIN_SIG_EVENT_QUE                 0U

#define DPC_OBJDET_DPU_RANGEPROC_PARAMSET_START_IDX                   DPC_OBJDEC_PARAMSET_START_IDX

#define DPC_OBJDET_DPU_RANGEPROC_EDMAOUT_FMT1_PING_CH                 EDMA_DSS_TPCC_A_EVT_HWA_DMA_REQ1
#define DPC_OBJDET_DPU_RANGEPROC_EDMAOUT_FMT1_PING_SHADOW             (DPC_OBJDET_EDMA_SHADOW_BASE + 2U)
#define DPC_OBJDET_DPU_RANGEPROC_EDMAOUT_FMT1_PING_EVENT_QUE          0U

#define DPC_OBJDET_DPU_RANGEPROC_EDMAOUT_FMT1_PONG_CH                 EDMA_DSS_TPCC_A_EVT_HWA_DMA_REQ2
#define DPC_OBJDET_DPU_RANGEPROC_EDMAOUT_FMT1_PONG_SHADOW             (DPC_OBJDET_EDMA_SHADOW_BASE + 3U)
#define DPC_OBJDET_DPU_RANGEPROC_EDMAOUT_FMT1_PONG_EVENT_QUE          0U

#define DPC_OBJDET_DPU_RANGEPROC_EDMAOUT_SIG_CH                       EDMA_DSS_TPCC_A_EVT_HWA_DMA_REQ3
#define DPC_OBJDET_DPU_RANGEPROC_EDMAOUT_SIG_SHADOW                   (DPC_OBJDET_EDMA_SHADOW_BASE + 4U)
#define DPC_OBJDET_DPU_RANGEPROC_EDMAOUT_SIG_EVENT_QUE                0U


//////////////////////////////////////////////
// DOPPLER DPU
//////////////////////////////////////////////
#define DPC_OBJDET_DPU_DOPPLERPROC_EDMA_INST_ID            DPC_OBJDET_EDMA_INSTANCE

#define DPC_OBJDET_DPU_DOPPLERPROCHWADDMA_PARAMSET_START_IDX      (DPC_OBJDET_DPU_RANGEPROC_PARAMSET_START_IDX + \
                                                                    DPU_RANGEPROCHWADDMA_NUM_HWA_PARAM_SETS)
#define DPU_DOPPLERPOCHWADDMA_DECOMP_NUM_HWA_PARAMSETS      DOPPLERPROCHWA_DDMA_DECOMP_NUM_HWA_PARAMSETS
#define DPU_DOPPLERPOCHWADDMA_DOPPLER_NUM_HWA_PARAMSETS     DOPPLERPROCHWA_DDMA_DOPPLER_NUM_HWA_PARAMSETS
#define DPU_DOPPLERPOCHWADDMA_SUMTX_NUM_HWA_PARAMSETS       2
#define DPU_DOPPLERPOCHWADDMA_AZIM_NUM_HWA_PARAMSETS        DOPPLERPROCHWA_DDMA_AZIMCFAR_NUM_HWA_PARAMSETS
#define DPU_DOPPLERPROCHWADDMA_NUM_HWA_PARAM_SETS           DPU_DOPPLERPOCHWADDMA_DECOMP_NUM_HWA_PARAMSETS + \
                                                            DPU_DOPPLERPOCHWADDMA_DOPPLER_NUM_HWA_PARAMSETS + \
                                                            DPU_DOPPLERPOCHWADDMA_AZIM_NUM_HWA_PARAMSETS

/* EDMA channels */
#define EDMA_DOPPLERPROC_DECOMP_IN_PING            EDMA_DSS_TPCC_A_EVT_CBUFF_DMA_REQ0
#define EDMA_DOPPLERPROC_DECOMP_IN_PONG            EDMA_DSS_TPCC_A_EVT_CBUFF_DMA_REQ1

/*This has to match the HWA DMA number*/
#define EDMA_DOPPLERPROC_DECOMP_OUT_PING           EDMA_DSS_TPCC_A_EVT_HWA_DMA_REQ4

/*This has to match the HWA DMA number*/
#define EDMA_DOPPLERPROC_DECOMP_OUT_PONG           EDMA_DSS_TPCC_A_EVT_HWA_DMA_REQ5

/* Free channels */
#define EDMA_DOPPLERPROC_DECOMP_IN_HOTSIG_PING     EDMA_DSS_TPCC_A_EVT_CBUFF_DMA_REQ2
#define EDMA_DOPPLERPROC_DECOMP_IN_HOTSIG_PONG     EDMA_DSS_TPCC_A_EVT_CBUFF_DMA_REQ3
// #define EDMA_DOPPLERPROC_DECOMP_OUT_HOTSIG         EDMA_DSS_TPCC_A_EVT_HWA_DMA_REQ6

#define EDMA_DOPPLERPROC_DOPPLER_IN_PING           EDMA_DSS_TPCC_A_EVT_HWA_DMA_REQ6
#define EDMA_DOPPLERPROC_DOPPLER_IN_PONG           EDMA_DSS_TPCC_A_EVT_HWA_DMA_REQ7

#define EDMA_DOPPLERPROC_DOPPLER_IN_HOTSIG_PING    EDMA_DSS_TPCC_A_EVT_HWA_DMA_REQ8
#define EDMA_DOPPLERPROC_DOPPLER_IN_HOTSIG_PONG    EDMA_DSS_TPCC_A_EVT_HWA_DMA_REQ9
// #define EDMA_DOPPLERPROC_DOPPLER_OUT_HOTSIG        EDMA_DSS_TPCC_A_EVT_HWA_DMA_REQ13

#define EDMA_DOPPLERPROC_MAXSUBBAND_OUT_PING       EDMA_DSS_TPCC_A_EVT_HWA_DMA_REQ10
#define EDMA_DOPPLERPROC_MAXSUBBAND_OUT_PONG       EDMA_DSS_TPCC_A_EVT_HWA_DMA_REQ11

#define EDMA_DOPPLERPROC_SUMTX_OUT_PING            EDMA_DSS_TPCC_A_EVT_HWA_DMA_REQ20
#define EDMA_DOPPLERPROC_SUMTX_OUT_PONG            EDMA_DSS_TPCC_A_EVT_HWA_DMA_REQ21

#define EDMA_DOPPLERPROC_EXTRACT_OBJECT_LIST       EDMA_DSS_TPCC_A_EVT_RTIA_DMA_REQ0

/*EDMA shadow channels*/
#define EDMA_DOPPLERPROC_DECOMP_IN_PING_SHADOW              (DPC_OBJDET_EDMA_SHADOW_BASE + 5U)
#define EDMA_DOPPLERPROC_DECOMP_IN_PONG_SHADOW              (DPC_OBJDET_EDMA_SHADOW_BASE + 6U)
#define EDMA_DOPPLERPROC_DECOMP_OUT_PING_SHADOW             (DPC_OBJDET_EDMA_SHADOW_BASE + 7U)
#define EDMA_DOPPLERPROC_DECOMP_OUT_PONG_SHADOW             (DPC_OBJDET_EDMA_SHADOW_BASE + 8U)
#define EDMA_DOPPLERPROC_DECOMP_IN_HOTSIG_PING_SHADOW       (DPC_OBJDET_EDMA_SHADOW_BASE + 9U)
#define EDMA_DOPPLERPROC_DECOMP_IN_HOTSIG_PONG_SHADOW       (DPC_OBJDET_EDMA_SHADOW_BASE + 10U)

#define EDMA_DOPPLERPROC_DOPPLER_IN_PING_SHADOW             (DPC_OBJDET_EDMA_SHADOW_BASE + 11U)
#define EDMA_DOPPLERPROC_DOPPLER_IN_PONG_SHADOW             (DPC_OBJDET_EDMA_SHADOW_BASE + 12U)
#define EDMA_DOPPLERPROC_DOPPLER_IN_HOTSIG_PING_SHADOW      (DPC_OBJDET_EDMA_SHADOW_BASE + 15U)
#define EDMA_DOPPLERPROC_DOPPLER_IN_HOTSIG_PONG_SHADOW      (DPC_OBJDET_EDMA_SHADOW_BASE + 16U)

#define EDMA_DOPPLERPROC_MAXSUBBAND_OUT_PING_SHADOW         (DPC_OBJDET_EDMA_SHADOW_BASE + 17U)
#define EDMA_DOPPLERPROC_MAXSUBBAND_OUT_PONG_SHADOW         (DPC_OBJDET_EDMA_SHADOW_BASE + 18U)

#define EDMA_DOPPLERPROC_SUMTX_OUT_PING_SHADOW              (DPC_OBJDET_EDMA_SHADOW_BASE + 23U)
#define EDMA_DOPPLERPROC_SUMTX_OUT_PONG_SHADOW              (DPC_OBJDET_EDMA_SHADOW_BASE + 24U)

#define EDMA_DOPPLERPROC_EXTRACT_OBJECT_LIST_SHADOW         (DPC_OBJDET_EDMA_SHADOW_BASE + 56U)

//////////////////////////////////////////////
// RANGE CFAR DPU
//////////////////////////////////////////////
#define DPC_OBJDET_DPU_RANGECFARPROC_EDMA_INST_ID            DPC_OBJDET_EDMA_INSTANCE

#define DPC_OBJDET_DPU_RANGECFARPROCHWADDMA_PARAMSET_START_IDX      (DPC_OBJDET_DPU_DOPPLERPROCHWADDMA_PARAMSET_START_IDX + \
                                                                    DPU_DOPPLERPROCHWADDMA_NUM_HWA_PARAM_SETS)
#define DPU_RANGECFARPROCHWADDMA_NUM_HWA_PARAMSETS      2U

/* EDMA channels */
#define DPC_OBJDET_DPU_RANGECFARPROC_EVENT_QUE  0U

#define EDMA_RANGECFARPROC_CFAR_IN_PING            EDMA_DSS_TPCC_A_EVT_CBUFF_DMA_REQ4
#define EDMA_RANGECFARPROC_CFAR_IN_PONG            EDMA_DSS_TPCC_A_EVT_CBUFF_DMA_REQ5
#define EDMA_RANGECFARPROC_CFAR_IN_HOTSIG_PING     EDMA_DSS_TPCC_A_EVT_HWA_DMA_REQ28
#define EDMA_RANGECFARPROC_CFAR_IN_HOTSIG_PONG     EDMA_DSS_TPCC_A_EVT_HWA_DMA_REQ29

/*This has to match the HWA DMA number*/
#define EDMA_RANGECFARPROC_CFAR_OUT_PING           EDMA_DSS_TPCC_A_EVT_HWA_DMA_REQ30

/*This has to match the HWA DMA number*/
#define EDMA_RANGECFARPROC_CFAR_OUT_PONG           EDMA_DSS_TPCC_A_EVT_HWA_DMA_REQ31

/* EDMA Shadow channels */
#define EDMA_RANGECFARPROC_CFAR_IN_PING_SHADOW            (DPC_OBJDET_EDMA_SHADOW_BASE + 33U)
#define EDMA_RANGECFARPROC_CFAR_IN_PONG_SHADOW            (DPC_OBJDET_EDMA_SHADOW_BASE + 34U)

/*This has to match the HWA DMA number*/
#define EDMA_RANGECFARPROC_CFAR_OUT_PING_SHADOW           (DPC_OBJDET_EDMA_SHADOW_BASE + 35U)

/*This has to match the HWA DMA number*/
#define EDMA_RANGECFARPROC_CFAR_OUT_PONG_SHADOW           (DPC_OBJDET_EDMA_SHADOW_BASE + 36U)

#define EDMA_RANGECFARPROC_CFAR_IN_HOTSIG_PING_SHADOW     (DPC_OBJDET_EDMA_SHADOW_BASE + 37U)
#define EDMA_RANGECFARPROC_CFAR_IN_HOTSIG_PONG_SHADOW     (DPC_OBJDET_EDMA_SHADOW_BASE + 38U)

/* EDMA to copy the intersection objects to L2. */
#define EDMA_OBJECTDETECTIONDPC_INTERSECT_DETOBJS          (EDMA_DSS_TPCC_A_EVT_RTIA_DMA_REQ1)
#define EDMA_OBJECTDETECTIONDPC_INTERSECT_DETOBJS_SHADOW   (DPC_OBJDET_EDMA_SHADOW_BASE + 55U)


/*************************LVDS streaming EDMA resources*******************************/

/*EDMA instance used*/
#define MMW_LVDS_STREAM_EDMA_INSTANCE            EDMA_DRV_INST_DSS_B
#define MMW_LVDS_STREAM_EDMA_SHADOW_BASE         EDMA_NUM_DMA_CHANNELS

/* CBUFF EDMA trigger channels */
#define MMW_LVDS_STREAM_CBUFF_EDMA_CH_0          EDMA_DSS_TPCC_B_EVT_CBUFF_DMA_REQ0
#define MMW_LVDS_STREAM_CBUFF_EDMA_CH_1          EDMA_DSS_TPCC_B_EVT_CBUFF_DMA_REQ1

/* HW Session*/
#define MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_0     EDMA_DSS_TPCC_B_EVT_FREE_0
#define MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_1     EDMA_DSS_TPCC_B_EVT_RTIA_DMA_REQ0
#define MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_2     EDMA_DSS_TPCC_B_EVT_RTIA_DMA_REQ1
#define MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_3     EDMA_DSS_TPCC_B_EVT_RTIA_DMA_REQ2
#define MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_4     EDMA_DSS_TPCC_B_EVT_RTIA_DMA_REQ3
#define MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_5     EDMA_DSS_TPCC_B_EVT_RTIB_DMA_REQ0
#define MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_6     EDMA_DSS_TPCC_B_EVT_RTIB_DMA_REQ1
#define MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_7     EDMA_DSS_TPCC_B_EVT_RTIB_DMA_REQ2
#define MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_8     EDMA_DSS_TPCC_B_EVT_RTIB_DMA_REQ3
#define MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_9     EDMA_DSS_TPCC_B_EVT_WDT_DMA_REQ0
#define MMW_LVDS_STREAM_HW_SESSION_EDMA_CH_10    EDMA_DSS_TPCC_B_EVT_WDT_DMA_REQ1

/* SW Session*/
#define MMW_LVDS_STREAM_SW_SESSION_EDMA_CH_0     EDMA_DSS_TPCC_B_EVT_WDT_DMA_REQ2
#define MMW_LVDS_STREAM_SW_SESSION_EDMA_CH_1     EDMA_DSS_TPCC_B_EVT_WDT_DMA_REQ3
#define MMW_LVDS_STREAM_SW_SESSION_EDMA_CH_2     EDMA_DSS_TPCC_B_EVT_MCRC_DMA_REQ0

/*shadow*/
/*shadow CBUFF trigger channels*/
#define MMW_LVDS_STREAM_CBUFF_EDMA_SHADOW_CH_0   (MMW_LVDS_STREAM_EDMA_SHADOW_BASE + 0U)
#define MMW_LVDS_STREAM_CBUFF_EDMA_SHADOW_CH_1   (MMW_LVDS_STREAM_EDMA_SHADOW_BASE + 1U)

/* HW Session*/
#define MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_0   (MMW_LVDS_STREAM_EDMA_SHADOW_BASE + 2U)
#define MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_1   (MMW_LVDS_STREAM_EDMA_SHADOW_BASE + 3U)
#define MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_2   (MMW_LVDS_STREAM_EDMA_SHADOW_BASE + 4U)
#define MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_3   (MMW_LVDS_STREAM_EDMA_SHADOW_BASE + 5U)
#define MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_4   (MMW_LVDS_STREAM_EDMA_SHADOW_BASE + 6U)
#define MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_5   (MMW_LVDS_STREAM_EDMA_SHADOW_BASE + 7U)
#define MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_6   (MMW_LVDS_STREAM_EDMA_SHADOW_BASE + 8U)
#define MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_7   (MMW_LVDS_STREAM_EDMA_SHADOW_BASE + 9U)
#define MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_8   (MMW_LVDS_STREAM_EDMA_SHADOW_BASE + 10U)
#define MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_9   (MMW_LVDS_STREAM_EDMA_SHADOW_BASE + 11U)
#define MMW_LVDS_STREAM_HW_SESSION_EDMA_SHADOW_CH_10  (MMW_LVDS_STREAM_EDMA_SHADOW_BASE + 12U)

/* SW Session*/
#define MMW_LVDS_STREAM_SW_SESSION_EDMA_SHADOW_CH_0   (EDMA_NUM_DMA_CHANNELS + 13U)
#define MMW_LVDS_STREAM_SW_SESSION_EDMA_SHADOW_CH_1   (EDMA_NUM_DMA_CHANNELS + 14U)
#define MMW_LVDS_STREAM_SW_SESSION_EDMA_SHADOW_CH_2   (EDMA_NUM_DMA_CHANNELS + 15U)
/*************************LVDS streaming EDMA resources END*******************************/



#ifdef __cplusplus
}
#endif

#endif /* MMW_DEMO_RES_H */
